# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "email" : "admin@admin.com",
  "password" : "123456"
}

###
POST http://localhost:8000/entradas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "titulo":"primer post",
  "contenido" :"este es el contenido",
  "fechaPub" : "2022-09-15",
  "categoria" : {
    "id":2,
    "nombre" : "categoria"
  },
  "tags": [{
    "id":"3",
    "nombre" : "tag1"
  },{
    "nombre": "nueva etiqueta"
  }]

}

###
GET http://localhost:8000/entradas/11
